/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewDataDialog: typeof import('./src/components/AddNewDataDialog.vue')['default']
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppProgressBar: typeof import('./src/components/AppProgressBar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    Message: typeof import('primevue/message')['default']
    ProductOverviewWidget: typeof import('./src/components/dashboard/ProductOverviewWidget.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RecentActivityWidget: typeof import('./src/components/dashboard/RecentActivityWidget.vue')['default']
    RegionSelector: typeof import('./src/components/RegionSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./src/components/dashboard/SalesTrendWidget.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
