/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewData: typeof import('./src/components/AddNewData.vue')['default']
    AddNewDataDialog: typeof import('./src/components/AddNewDataDialog.vue')['default']
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppCatalogTabView: typeof import('./src/components/AppCatalogTabView.vue')['default']
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppMenubar: typeof import('./src/components/AppMenubar.vue')['default']
    AppProgressBar: typeof import('./src/components/AppProgressBar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    BreadCrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ColumnVisibilitySelector: typeof import('./src/components/ColumnVisibilitySelector.vue')['default']
    CompPage1TabView: typeof import('./src/components/CompPage1TabView.vue')['default']
    copy: typeof import('./src/components/ColumnVisibilitySelector copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    DynamicFormField: typeof import('./src/components/DynamicFormField.vue')['default']
    DynamicFormLayout: typeof import('./src/components/DynamicFormLayout.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListViewP1: typeof import('./src/components/ListViewP1.vue')['default']
    Message: typeof import('primevue/message')['default']
    ObjectFieldPopover: typeof import('./src/components/ObjectFieldPopover.vue')['default']
    P1_ListView: typeof import('./src/components/P1_ListView.vue')['default']
    P1_TabView: typeof import('./src/components/P1_TabView.vue')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    ProductOverviewWidget: typeof import('./src/components/dashboard/ProductOverviewWidget.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RecentActivityWidget: typeof import('./src/components/dashboard/RecentActivityWidget.vue')['default']
    RichEditPopover: typeof import('./src/components/RichEditPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesTrendWidget: typeof import('./src/components/dashboard/SalesTrendWidget.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    TabViewP1: typeof import('./src/components/TabViewP1.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
